<?php $this->headScript()->captureStart() ?>
var mapWidth = <?php echo $this->map['mapWidth'] ?>,
mapHeight = <?php echo $this->map['mapHeight'] ?>,
maxPlayers = <?php echo $this->map['maxPlayers'] ?>,
name = '<?php echo $this->map['name'] ?>',
mapId = <?php echo $this->map['mapId'] ?>,
langId = <?php echo Zend_Registry::get('id_lang') ?>,
mapCastles = <?php echo Zend_Json::encode($this->mapCastles) ?>
<?php $this->headScript()->captureEnd() ?>
