<div class="table">
    <h2><?php echo $this->translate('Map list') ?></h2>
    <table>
        <th>Map name</th>
        <th>Max players</th>
        <th>Creation date</th>
        <th>Delete</th>
        <?php if (is_array($this->mapList)): ?>
            <?php foreach ($this->mapList as $map): ?>
                <tr id="<?php echo $map['mapId'] ?>" class="trlink">
                    <td><?php echo $map['name'] ?></td>
                    <td><?php echo $map['maxPlayers'] ?></td>
                    <td><?php echo Coret_View_Helper_Formatuj::date($map['date']) ?></td>
                    <td><div class="trash"></div></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<a class="button" id="create"><?php echo $this->translate('Create') ?></a>
