<div id="join" class="table">
    <h2><?php echo $this->translate('Join one of the games listed below') ?></h2>
    <table>
        <th><?php echo $this->translate('Map name') ?></th>
        <th><?php echo $this->translate('Game master') ?></th>
        <th><?php echo $this->translate('Number of players') ?></th>
        <th><?php echo $this->translate('Date') ?></th>
    </table>
</div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Create new game') ?></h2>
    <table id="new">
        <tr>
            <td id="form">
                <?php echo $this->form; ?>
            </td>
            <td id="img"></td>
        </tr>
    </table>
</div>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>

<?php $this->headScript()->captureStart() ?>
var info = '<?php echo $this->translate('There are no open games') ?>';
<?php $this->headScript()->captureEnd() ?>
