<div class="table">
    <h2><?php echo $this->translate('Select your color and team') ?></h2>
    <table id="playersingame">
        <th><?php echo $this->translate('Player color') ?></th>
        <th><?php echo $this->translate('Select your color') ?></th>
        <th><?php echo $this->translate('Human/AI') ?></th>
        <th><?php echo $this->translate('Select your team') ?></th>
        <?php foreach ($this->mapPlayers as $mapPlayerId => $mapPlayer): ?>
            <tr id="<?php echo $mapPlayerId ?>">
                <td class="td1">
                    <div>
                        <span style="color:<?php echo $mapPlayer['backgroundColor'] ?>;text-shadow: 2px 2px 0 <?php echo $mapPlayer['textColor'] ?>">
                            <?php echo $mapPlayer['shortName'] ?>
                        </span>
                    </div>
                </td>
                <td class="td2"></td>
                <td class="td3"></td>
                <td class="td4"></td>
            </tr>
        <?php endforeach ?>
    </table>
    <h2><?php echo $this->translate('Undecided') ?></h2>
    <table id="playersout"></table>
</div>
<div id="start" class="button"></div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Game settings') ?></h2>

    <div class="box">
        <p><?php echo $this->translate('Map') ?>: <span class="yellow"><?php echo $this->mapName ?></span></p>
        <p><?php echo $this->translate('Required number of players') ?>: <span
                class="yellow"><?php echo $this->game['numberOfPlayers'] ?></span></p>
        <p><?php echo $this->translate('Time limit') ?>: <span
                class="yellow"><?php echo $this->timeLimits[$this->game['timeLimit']] ?></span></p>
        <p><?php echo $this->translate('Limit of the number of turns') ?>:
            <span class="yellow"><?php if ($this->game['turnsLimit']): echo $this->game['turnsLimit'];
            else: echo $this->translate('no limit'); endif ?></p></span>
        <p><?php echo $this->translate('Time limit per turn') ?>: <span
                class="yellow"><?php echo $this->translate($this->turnTimeLimit[$this->game['turnTimeLimit']]) ?></span>
        </p>
    </div>
</div>
<a class="button" id="back">&laquo; <?php echo $this->translate('Back') ?></a>
