<div class="table">
    <h2><?php echo $this->translate('Select your color and team') ?></h2>
    <table id="playersingame">
        <tr>
            <th><?php echo $this->translate('Player color') ?></th>
            <th><?php echo $this->translate('Select your color') ?></th>
            <th></th>
            <th><?php echo $this->translate('Team') ?></th>
        </tr>
    </table>
    <h2><?php echo $this->translate('Undecided') ?></h2>
    <table id="playersout"></table>
</div>
<div id="start" class="button"></div>
<a class="button" id="back">&laquo; <?php echo $this->translate('Back') ?></a>
