<h1><?php echo $this->translate('Players') ?></h1>
<div>
    <?php echo $this->searchForm ?>
</div>
<div class="table">
    <h2><?php echo $this->translate('Search results') ?></h2>
    <table id="searchResults">
        <tr>
            <th><?php echo $this->translate('Player name') ?></th>
        </tr>
        <?php if (count($this->searchResults)): ?>
            <?php foreach ($this->searchResults as $row): ?>
                <tr class="trlink">
                    <td><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></td>
                    <td>
                        <a href="/<?php echo Zend_Registry::get('lang') ?>/players/add/friendId/<?php echo $row['playerId'] ?>"><?php echo $this->translate('Add to friends') ?></a>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>
