<div class="table">
    <h2><?php echo $this->translate('Tournaments list') ?></h2>
    <table id="tournamentList">
        <tr>
            <th>
                <div class="padding"><?php echo $this->translate('Start date') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Map name') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Participants limit') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Finished') ?></div>
            </th>
        </tr>
    </table>
</div>
