<div id="loadMenu"></div>
<div class="table">
    <h2><?php echo $this->translate('Games list') ?></h2>
    <table id="gameList">
        <tr>
            <th>
                <div class="padding"><?php echo $this->translate('Map name') ?></div>
                <div class="padding"><?php echo $this->translate('Pause date') ?></div>
            </th>
            <th>
                <?php echo $this->translate('Name') ?>
                <?php echo $this->translate('Color') ?>
                <?php echo $this->translate('Team') ?>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Turn nr') ?></div>
                <div class="padding"><?php echo $this->translate('Player turn') ?></div>
            </th>
            <th><?php echo $this->translate('Finish') ?> / <?php echo $this->translate('Delete') ?></th>
        </tr>
    </table>
</div>
