<?php if (isset($this->heroes[0])): ?>
    <div class="table">
        <h2><?php echo $this->translate('Hero statistics') ?>:</h2>

        <div class="box">
            <?php echo $this->translate('Attack points') ?>: <?php echo $this->heroes[0]['attackPoints'] ?></br>
            <?php echo $this->translate('Defense points') ?>: <?php echo $this->heroes[0]['defensePoints'] ?></br>
            <?php echo $this->translate('Number of moves') ?>: <?php echo $this->heroes[0]['numberOfMoves'] ?></br>
        </div>
    </div>
    <br/>
<?php endif ?>
<div class="table">
    <h2><?php echo $this->translate('Change name') ?>:</h2>
    <?php echo $this->form ?>
</div>
<!--<h2>--><?php //echo $this->translate('Artifacts') ?><!--:</h2>-->
<!--<div class="table" id="chest">-->
<!--    <h3>--><?php //echo $this->translate('Chest') ?><!--</h3>-->
<!--    <table>-->
<!--        <th>--><?php //echo $this->translate('Name') ?><!--</th>-->
<!--        <th>--><?php //echo $this->translate('Quantity') ?><!--</th>-->
<!--        --><?php //if (count($this->chest)): ?>
<!--            --><?php //foreach ($this->chest as $artifact): ?>
<!--                <tr>-->
<!--                    <td>--><?php //echo $this->artifacts[$artifact['artifactId']]['name'] ?><!--</td>-->
<!--                    <td>--><?php //echo $artifact['quantity'] ?><!--</td>-->
<!--                </tr>-->
<!--            --><?php //endforeach ?>
<!--        --><?php //endif ?>
<!--    </table>-->
<!--</div>-->
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>
