<?php $this->headScript()->captureStart() ?>

var debug = '<?php echo Zend_Registry::get('config')->debug ?>'

var lang = '<?php echo Zend_Registry::get('lang') ?>'
var langId = <?php echo Zend_Registry::get('id_lang') ?>

var gameId = <?php echo $this->gameId ?>;
var accessKey = '<?php echo $this->accessKey ?>';

var my = {
    color: '<?php echo $this->color ?>',
    id: <?php echo $this->id ?>,
    turn: <?php echo $this->myTurn ?>,
    game: <?php echo $this->myGame ?>,
    gold: <?php echo $this->gold ?>,
    battleSequence: <?php echo Zend_Json::encode($this->battleSequence) ?>
}

var timeLimits = <?php echo Zend_Json::encode(Application_Model_Limit::timeLimits()); ?>;
var turnTimeLimit = <?php echo Zend_Json::encode(Application_Model_Limit::turnTimeLimit()); ?>;
var game = <?php echo Zend_Json::encode($this->game) ?>;
var translations = <?php echo $this->translations() ?>;
var ruins = <?php echo Zend_Json::encode($this->ruins); ?>;
var units = <?php echo Zend_Json::encode($this->units); ?>;
var towers = <?php echo Zend_Json::encode($this->towers); ?>;
<!--var artifacts = --><?php //echo Zend_Json::encode($this->artifacts); ?><!--;-->
var players = <?php echo Zend_Json::encode($this->players); ?>;
var castles = <?php echo Zend_Json::encode($this->castlesSchema); ?>;
var capitals = <?php echo Zend_Json::encode($this->capitals); ?>;
var chatHistory = <?php echo Zend_Json::encode($this->chatHistory); ?>;
var turnHistory = <?php echo Zend_Json::encode($this->turnHistory); ?>;
var terrain = <?php echo Zend_Json::encode($this->terrain); ?>;
var fieldsOryginal = <?php echo Zend_Json::encode($this->fields); ?>;
<?php $this->headScript()->captureEnd() ?>
