<?php $this->headScript()->captureStart() ?>

var debug = '<?php echo Zend_Registry::get('config')->debug ?>'

var lang = '<?php echo Zend_Registry::get('lang') ?>'
var langId = <?php echo Zend_Registry::get('id_lang') ?>

var gameId = <?php echo $this->gameId ?>;
var accessKey = '<?php echo $this->accessKey ?>';

var my = {'id':<?php echo $this->playerId ?>};

var translations = <?php echo $this->translations() ?>;

<?php $this->headScript()->captureEnd() ?>
