<div class="table">
    <h2><?php echo $this->translate('Select your color and team') ?></h2>
    <div><?php echo $this->translate('Team') ?> A</div>
    <table class="playersingame" id="1">
        <tr>
            <th><?php echo $this->translate('Player color') ?></th>
            <th><?php echo $this->translate('Select your color') ?></th>
            <th></th>
        </tr>
    </table>
    <div><?php echo $this->translate('Team') ?> B</div>
    <table class="playersingame" id="2">
        <tr>
            <th><?php echo $this->translate('Player color') ?></th>
            <th><?php echo $this->translate('Select your color') ?></th>
            <th></th>
        </tr>
    </table>
    <h2><?php echo $this->translate('Undecided') ?></h2>
    <table id="playersout"></table>
</div>
<div id="start" class="button buttonColors"></div>
