<h1><?php echo $this->translate('Messages') ?></h1>

<div class="table">
    <h2><?php echo $this->translate('Conversations') ?></h2>
    <table id="threads">
        <tr>
            <th><?php echo $this->translate('Player name') ?></th>
            <th><?php echo $this->translate('Date') ?></th>
            <th><?php echo $this->translate('Messages') ?></th>
        </tr>
        <?php if (count($this->threads)): ?>
            <?php foreach ($this->threads as $row): ?>
                <tr class="trlink<?php if ($row['read']): echo ' read'; endif ?>" id="<?php echo $row['playerId'] ?>">
                    <td><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></td>
                    <td><?php echo Coret_View_Helper_Formatuj::date($row['max']) ?></td>
                    <td><?php echo $row['read'] . '/' . $row['messages'] ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<?php echo $this->paginationControl($this->threads, 'Sliding', 'pagination_control.phtml'); ?>
<a href="/" class="button">&laquo; <?php echo $this->translate('Back') ?></a>
