<h1><?php echo $this->translate('Messages') ?></h1>

<div class="table">
    <h2><?php echo $this->translate('Messages list') ?></h2>
    <table id="messages">
        <?php if (count($this->messages)): ?>
            <?php foreach ($this->messages as $row): ?>
                <tr class="trlink" id="<?php echo $row['playerId'] ?>">
                    <td>
                        <div class="date"><?php echo Coret_View_Helper_Formatuj::date($row['date']) ?></div>
                        <div class="name"><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></div>
                        <div class="message"><?php echo $row['message'] ?></div>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>
<a href="/" class="button">&laquo; <?php echo $this->translate('Back') ?></a>
