<div id="view-content">
    <p>
        <a href="<?php echo $this->url(array('action' => 'registration')) ?>"
           class="button buttonColors"><?php echo $this->translate('Register') ?></a>
        <a href="<?php echo $this->loginUrl ?>" class="button buttonColors"><?php echo $this->translate('Facebook login') ?></a>
    </p>
</div>
<div class="login">
    <?php
    echo $this->form;
    echo $this->langForm;
    ?>
</div>