<?php echo $this->doctype() ?>
<html>
<head>
    <?php
    echo $this->headMeta() . "\n";
    echo $this->headTitle() . "\n";
    echo $this->headScript() . "\n";
    echo $this->headLink() . "\n";
    ?>
</head>
<body>
<div id="main">
    <div id="bg">
        <div id="page">
            <div id="menuBox">
                <div id="menuTop">
                    <div id="title"><?php echo $this->placeholder('title') ?></div>
                    <?php echo $this->placeholder('logout') ?>
                    <div id="envelope"></div>
                </div>
                <div id="menu"></div>
            </div>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->placeholder('sound') ?>
</body>
</html>