<?php echo $this->doctype() ?>
<html>
<head>
    <?php
    echo $this->headMeta() . "\n";
    echo $this->headTitle() . "\n";
    echo $this->headScript() . "\n";
    echo $this->headLink() . "\n";
    ?>
</head>
<body>
<div id="bg">
    <div id="page">
        <div id="menuTop">
            Wars of Fate
            <?php echo $this->placeholder('logout') ?>
        </div>
        <div id="content">
            <?php echo $this->placeholder('mainMenu') ?>
            <?php echo $this->placeholder('version') ?>
            <?php echo $this->layout()->content ?>
        </div>
    </div>
</div>
</body>
</html>