<?php echo $this->doctype() ?>
<html>
<head>
    <?php
    echo $this->headMeta() . "\n";
    echo $this->headTitle() . "\n";
    echo $this->headScript() . "\n";
    echo $this->headLink() . "\n";
    ?>
</head>
<body>
<div id="chatBox" class="box disabled">
    <div id="title"><?php echo $this->placeholder('chatTitle') ?></div>
    <div class="close">&#x25B6</div>
    <input id="friendId" value=""/>

    <div id="chatWindow">
        <div id="chatContent"></div>
    </div>
    <div id="chatInput">
        <input type="text" name="msg" id="msg"/>

        <div id="send" class="button buttonColors"> ></div>
        <div id="chatTitle"></div>
    </div>
</div>
<div id="friendsBox" class="box">
    <div id="title"><?php echo $this->placeholder('friendsTitle') ?></div>
    <div class="close">&#x25B6</div>
    <div id="friends"><?php echo $this->placeholder('friends') ?></div>
</div>
<div id="bg">
    <div id="page">
        <div id="menuBox">
            <div id="menuTop">
                <div id="title">Wars of Fate</div>
                <?php echo $this->placeholder('logout') ?>
            </div>
            <?php echo $this->placeholder('mainMenu') ?>
            <div id="envelope"></div>
        </div>
        <div id="content">
            <?php echo $this->placeholder('version') ?>
            <?php echo $this->layout()->content ?>
        </div>
    </div>
</div>

</body>
</html>