<div id="editor">
    <div id="mapBox" class="box">
        <div id="map">
            <div id="lens"></div>
        </div>
        <div id="terrain">
            <?php echo $this->translate('Terrain') ?>: <span id="coord" class="font-gold"></span>
        </div>
        <a class="button buttonColors" id="castle"><?php echo $this->translate('Castle') ?></a>
        <a class="button buttonColors" id="ruin"><?php echo $this->translate('Ruin') ?></a>
        <a class="button buttonColors" id="tower"><?php echo $this->translate('Tower') ?></a>
        <a class="button buttonColors" id="road"><?php echo $this->translate('Road') ?></a>
        <a class="button buttonColors" id="forest"><?php echo $this->translate('Forest') ?></a>
        <a class="button buttonColors" id="swamp"><?php echo $this->translate('Swamp') ?></a>
        <a class="button buttonColors" id="eraser"><?php echo $this->translate('Eraser') ?></a>
        <a class="button buttonColors" id="up"><?php echo $this->translate('Up') ?></a>
        <a class="button buttonColors" id="down"><?php echo $this->translate('Down') ?></a>
        <a class="button buttonColors" id="texture"><?php echo $this->translate('Texture') ?></a>
    </div>
    <div id="mainMenu" class="box">
        <div id="exit" class="iconButton buttonColors">
            <span class="Centerer"></span>
            <img src="/img/game/exit.png" alt="<?php echo $this->translate('Exit editor') ?>"/>
        </div>
        <div id="publish" class="button buttonColors"><?php echo $this->translate('Publish') ?></div>
    </div>
</div>
