<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?php
    echo $this->headTitle() . "\n";
    echo $this->headLink() . "\n";
    echo $this->headScript() . "\n";
    echo $this->headMeta() . "\n";
    ?>
</head>
<body>
<div id="game">
    <div id="board"></div>
    <div id="editorMenu" class="box">
        <a class="button buttonColors" id="castle"><?php echo $this->translate('Castle') ?></a>
        <a class="button buttonColors" id="ruin"><?php echo $this->translate('Ruin') ?></a>
        <a class="button buttonColors" id="tower"><?php echo $this->translate('Tower') ?></a>
        <a class="button buttonColors" id="road"><?php echo $this->translate('Road') ?></a>
        <a class="button buttonColors" id="forest"><?php echo $this->translate('Forest') ?></a>
        <a class="button buttonColors" id="swamp"><?php echo $this->translate('Swamp') ?></a>
        <a class="button buttonColors" id="eraser"><?php echo $this->translate('Eraser') ?></a>
        <a class="button buttonColors" id="up"><?php echo $this->translate('Up') ?></a>
        <a class="button buttonColors" id="down"><?php echo $this->translate('Down') ?></a>
    </div>
    <div id="playersBox" class="box">
        <div id="exit" class="iconButton buttonColors">
            <span class="Centerer"></span>
            <img src="/img/game/exit.png" alt="<?php echo $this->translate('Exit game') ?>"/>
        </div>
    </div>
</div>
</body>
</html>
<?php echo $this->layout()->content; ?>
