<div id="game">
    <div id="map">
        <div id="lens"></div>
    </div>
    <div id="terrain"></div>
    <div id="gold" class="button buttonColors">
        <div class="text-right font-gold" id="value">0</div>
        <div><?php echo $this->translate('Gold') ?></div>
    </div>
    </div>

    <div id="exit" class="iconButton buttonColors">
        <span class="Centerer"></span>
        <img src="/img/game/exit.png" alt="<?php echo $this->translate('Exit game') ?>"/>
    </div>

    <div id="nextTurn" class="iconButton buttonColors"><span id="turnNumber"></span> >></div>

    <div id="armyButtons">
        <div id="nextArmy" class="iconButton buttonColors buttonOff">
            <div title="<?php echo $this->translate('Find next army') ?> (n) "></div>
        </div>
        <div id="armyStatus" class="iconButton buttonColors buttonOff">
            <div title="<?php echo $this->translate('Army status') ?> (s) "></div>
        </div>
    </div>
</div>
<div id="loading"><?php echo $this->translate('Loading') ?>...</div>
