<div id="game">
    <div id="terrain"></div>
    <div id="gold" class="button buttonColors">
        <div id="value">0</div>
        <div id="description"><?php echo $this->translate('Gold') ?></div>
    </div>

    <div id="menuButtons">
        <div id="nextTurn" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Next turn') ?> (t) "></div>
        </div>
        <div id="showMenu" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Show menu') ?> (m) "></div>
        </div>
    </div>

    <div id="armyButtons">
        <div id="nextArmy" class="iconButton buttonColors buttonOff">
            <div title="<?php echo $this->translate('Find next army') ?> (n) "></div>
        </div>
        <div id="armyStatus" class="iconButton buttonColors buttonOff">
            <div title="<?php echo $this->translate('Army status') ?> (s) "></div>
        </div>
    </div>
</div>
<div id="battle"></div>
<div id="loading"><?php echo $this->translate('Loading') ?>...</div>
<div id="gameMenu">
    <div class="row">
        <div class="description"><?php echo $this->translate('Exit game') ?></div>
        <div id="exit" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Exit game') ?>"></div>
        </div>
    </div>
    <div class="row">
        <div class="description"><?php echo $this->translate('Surrender') ?></div>
        <div id="surrender" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Surrender') ?>"></div>
        </div>
    </div>
    <div class="row">
        <div class="description"><?php echo $this->translate('Show statistics') ?></div>
        <div id="statistics" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Statistics') ?>"></div>
        </div>
    </div>
    <div class="row">
        <div class="description"><?php echo $this->translate('Show other players moves') ?></div>
        <div id="show" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Show others') ?>"></div>
        </div>
    </div>
    <div class="row">
        <div class="description"><?php echo $this->translate('Turn sound on/off') ?></div>
        <div id="sound" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Sound') ?>"></div>
        </div>
    </div>
    <div class="row">
        <div class="description"><?php echo $this->translate('Toggle full screen') ?></div>
        <div id="fullScreen" class="iconButton buttonColors">
            <div title="<?php echo $this->translate('Full screen') ?>"></div>
        </div>
    </div>
    <div id="close" class="button buttonColors"><?php echo $this->translate('Close') ?></div>

</div>