<?php echo $this->doctype() ?>
<html>
<head>
    <?php
    echo $this->headMeta() . "\n";
    echo $this->headTitle() . "\n";
    echo $this->headLink() . "\n";
    echo $this->headScript() . "\n";
    ?>
</head>
<body>
<div id="page">
    <div id="title"><div><h1><?php echo $this->placeholder('title') ?></h1><p>strategic game</p></div></div>
    <div id="login">
        <?php echo $this->layout()->content; ?>
    </div>
    <div>
        <?php echo $this->placeholder('version') ?>
    </div>
</div>
</body>
</html>