<?php echo $this->doctype() ?>
<html>
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </body>
</html>