<?php $lang = Zend_Registry::get('lang'); ?>
<h1><?php echo $this->translate('Play') ?></h1>
<div class="table">
    <h2><?php echo $this->translate('Tutorial') ?></h2>

    <div class="bigLink">
        <a href="/<?php echo $lang ?>/tutorial/init">Start tutorial</a>
    </div>
</div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Multiplayer') ?></h2>

    <div class="bigLink">
        <a href="/<?php echo $lang ?>/new">Join/start game</a>
    </div>
</div>