<?php
if ($this->tutorial) {
    $number = $this->tutorial['tutorialNumber'] + 1;
    $tutorialLink = $this->translate('Continue tutorial') . '&nbsp;' . $number . '/3';
} else {
    $tutorialLink = $this->translate('Start tutorial') . ' 0/3';
}
?>
<div class="table">
    <h2><?php echo $this->translate('Tutorial') ?></h2>

    <div class="bigLink">
        <a id="tutorial"><?php echo $tutorialLink ?></a>
    </div>
</div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Multiplayer') ?></h2>

    <div class="bigLink">
        <a id="newGame"><?php echo $this->translate('Join / start game') ?></a>
    </div>
</div>
<a class="button" id="back">&laquo; <?php echo $this->translate('Back') ?></a>