<div class="table">
    <h2><?php echo $this->translate('Friends') ?></h2>
    <table id="friendsList">
        <tr>
            <th><?php echo $this->translate('Status') ?></th>
            <th><?php echo $this->translate('Friend name') ?></th>
            <th><?php echo $this->translate('Delete friend') ?></th>
        </tr>
    </table>
</div>
<a class="button" id="back">&laquo; <?php echo $this->translate('Back') ?></a>
