<h1><?php echo $this->translate('Friends') ?></h1>
<div class="table">
    <h2><?php echo $this->translate('Players list') ?></h2>
    <table>
        <tr>
            <th><?php echo $this->translate('Player name') ?></th>
        </tr>
        <?php if (count($this->friends)): ?>
            <?php foreach ($this->friends as $row): ?>
                <tr class="trlink">
                    <td><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<?php echo $this->paginationControl($this->friends, 'Sliding', 'pagination_control.phtml'); ?>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>
