<h1><?php echo $this->translate('Friends') ?></h1>
<div>
    <?php echo $this->searchForm ?>
</div>
<div class="table">
    <h2><?php echo $this->translate('Search results') ?></h2>
    <table>
        <tr>
            <th><?php echo $this->translate('Player name') ?></th>
        </tr>
        <?php if (count($this->searchResults)): ?>
            <?php foreach ($this->searchResults as $row): ?>
                <tr class="trlink">
                    <td><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></td>
                    <td>
                        <a href="/ <?php echo Zend_Registry::get('lang') ?>/friends/add/friendId/<?php echo $row['playerId'] ?>"><?php echo $this->translate('Add to friends') ?></a>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<div class="table">
    <h2><?php echo $this->translate('Friends list') ?></h2>
    <table>
        <tr>
            <th><?php echo $this->translate('Player name') ?></th>
        </tr>
        <?php if (count($this->friends)): ?>
            <?php foreach ($this->friends as $row): ?>
                <tr class="trlink">
                    <td><?php echo $row['firstName'] . ' ' . $row['lastName'] ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<?php echo $this->paginationControl($this->friends, 'Sliding', 'pagination_control.phtml'); ?>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>
