<div class="table">
    <h2><?php echo $this->translate('Change your data') ?>:</h2>
    <?php echo $this->formPlayer; ?>
</div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Change your e-mail') ?>:</h2>
    <?php echo $this->formEmail; ?>
</div>
<br>
<div class="table">
    <h2><?php echo $this->translate('Change your password') ?>:</h2>
    <?php echo $this->formPassword; ?>
</div>
