<div class="table">
    <h2><?php echo $this->translate('Player profile') . ' ' . $this->player['firstName'] . ' ' . $this->player['lastName'] ?></h2>
    <table>
        <tr>
            <th>
                <div class="padding"><?php echo $this->translate('Begin') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('End') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Number of rounds') ?></div>
            </th>
            <th>
                <div class="padding"><?php echo $this->translate('Score') ?></div>
            </th>
        </tr>
        <?php if (count($this->playerScores)): ?>
            <?php foreach ($this->playerScores as $row): ?>
                <tr class="trlink" id="<?php echo $row['gameId'] ?>">
                    <td><?php echo Coret_View_Helper_Formatuj::date($row['begin']) ?></td>
                    <td><?php echo Coret_View_Helper_Formatuj::date($row['end']) ?></td>
                    <td><?php echo $row['turnNumber'] ?></td>
                    <td><?php echo $row['score'] ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>

