<h1><?php echo $this->translate('Player profile') ?></h1>
<div class="table">
    <h2><?php echo $this->player['firstName'] . ' ' . $this->player['lastName'] ?></h2>
    <table>
        <?php if (count($this->playerScores)): ?>
            <?php foreach ($this->playerScores as $row): ?>
                <tr class="trlink" id="<?php echo $row['gameId'] ?>">
                    <td><?php echo $row['score'] ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </table>
</div>
<a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>

