<div class="table">
    <h2><?php echo $this->translate('Contact') ?></h2>
    <table class="contact">
        <tr>
            <td><?php echo $this->translate('Author') ?>:</td>
            <td>Bartosz Krzeszewski</td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Email address') ?>:</td>
            <td>bartek@bugpoint.pl</td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Mobile number') ?>:</td>
            <td>+48 727 694 292</td>
        </tr>
    </table>
</div>
