<div id="halloffameMenu"></div>
<div class="table">
    <h2><?php echo $this->translate('Hall of Fame') ?></h2>
    <table id="halloffameList">
        <tr>
            <th><?php echo $this->translate('Place') ?></th>
            <th><?php echo $this->translate('Player name') ?></th>
            <th><?php echo $this->translate('Score') ?></th>
            <th><?php echo $this->translate('Map name') ?></th>
        </tr>
    </table>
</div>